version: 1.0.{build}
configuration:
- Debug
- Release
assembly_info:
  patch: true
  file: '**\spv3/loader\src\properties\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
assembly_info:
  patch: true
  file: '**\hxe\kernel\src\properties\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
dotnet_csproj:
  patch: true
  file: '**\spv3\loader\src\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
dotnet_csproj:
  patch: true
  file: '**\hxe\kernel\src\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
install:
- git submodule init
- git submodule update
nuget:
  project_feed: true
before_build:
- nuget restore
build:
  project: '**\spv3\loader\src\spv3.sln'
  parallel: true
  verbosity: minimal